### ISSUE TITLE
delegateEvents is failing with TypeError: '[object Object]' is not a valid argument for 'Function.prototype.apply' when the optional events argument is provided.

### ISSUE THREAD

**Issue by suprememoocow** [nervetattoo/backbone.keys#2]
Hi,

For reasons that I haven't quite figured out yet, I'm getting a failure in phantomjs that I'm not seeing in Chrome or Safari.

```
An unexpected error occurred: 'TypeError: '[object Object]' is not a valid argument for 'Function.prototype.apply' (evaluating 'oldDelegateEvents.apply')' in http://localhost/js/backbone.keys/backbone.keys.js:99
```

The problem appears to be when an object hash of events is passed into delegateEvents, that object is passed directly into 

``` javascript
oldDelegateEvents.apply(this, (events || []));
```

However, `Function.prototype.apply()` second parameter is an _array of arguments_, whereas when events is non-falsey a hash is passed in, causing the TypeError.

The fix I've made locally is to change the call to:

``` javascript
oldDelegateEvents.apply(this, Array.prototype.slice.apply(arguments));
```

This works nicely for me.

Thanks
Andrew

**Comment by nervetattoo** [comment]
How do you trigger this? Could you show me the code your'e running via phantom?

**Comment by nervetattoo** [comment]
Slicing the arguments object is a good idea anyway so I've just implemented it, even though I was unable to reprodue the error message when i ran the testcase (using phantomjs).
