### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by DmitryOlkhovoi** [nervetattoo/backbone.keys#3]
Pls update you repo on the bower. There requires lodash, but backbone requires underscore. So we anyway can to use lodash, but rather require underscore.

**Comment by nervetattoo** [comment]
Where is the dependency on lodash that you're talking about? This library doesn't define any dependencies in the component.json actually, you need to provide Backbone your self.

**Comment by DmitryOlkhovoi** [comment]
Check you bower repo

**Comment by nervetattoo** [comment]
So this is the screenshot of installing backbone.keys over Bower, proving that there is no lodash required:

![screen shot 2014-07-24 at 15 27 12](https://cloud.githubusercontent.com/assets/45449/3688441/5e283588-1336-11e4-9f12-e595d224cb3a.png)

I'm closing this, just reopen if you meant something else.
