### ISSUE TITLE
events not unbinding

### ISSUE THREAD

**Issue by linus-amg** [nervetattoo/backbone.keys#4]
hi,
im using the latest version of marionette and backbone and it seems like the events never get unbinded from the view, is that right?

**Comment by nervetattoo** [comment]
Events are unbound in the patched [undelegateEvents](https://github.com/nervetattoo/backbone.keys/blob/master/backbone.keys.js#L113) method.
So it depends on how you are handling your views on teardown.
I've not used Marionette my self so I don't know how it handles view life cycle.
